<?php

declare(strict_types=1);

namespace Tests\Authorization;

use App\Http\Requests\AuthorizationRequest;
use Faker\Factory;
use Tests\TestCase;
use Validator;

final class AuthorizationRequestTest extends TestCase
{
    /**
     * @var array $rules
     */
    private array $rules;

    /**
     * @var bool $isInit
     */
    private bool $isInit = true;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        if ($this->isInit) {
            $this->isInit = false;
            $this->rules = (new AuthorizationRequest())->rules();
        }
    }

    /**
     * Проверка ошибок валидации.
     *
     * @test
     *
     * @dataProvider validationFailsProvider
     *
     * @param array $input
     */
    public function testValidationFails(array $input): void
    {
        /** @var \Illuminate\Validation\Validator $v */
        $v = Validator::make($input, $this->rules);

        $this->assertTrue($v->fails());
        $this->assertEquals(1, $v->errors()->count());
    }

    /**
     * @return array
     */
    public function validationFailsProvider(): array
    {
        $faker = Factory::create( 'ru_RU');
        return [
            [
                'data' => [
                    'password' => $faker->password,
                ],
            ],
            [
                'data' => [
                    'login' => $faker->email,
                ],
            ],
            [
                'data' => [
                    'login' => $faker->lastName,
                    'password' => $faker->password,
                ],
            ],
        ];
    }

    /**
     * Проверка валидации.
     *
     * @test
     *
     * @dataProvider validationProvider
     *
     * @param array $input
     */
    public function testValidation(array $input): void
    {
        /** @var \Illuminate\Validation\Validator $v */
        $v = Validator::make($input, $this->rules);

        $this->assertFalse($v->fails());
    }

    /**
     * @return array
     */
    public function validationProvider(): array
    {
        $faker = Factory::create( 'ru_RU');

        return [
            [
                'data' => [
                    'login' => $faker->email,
                    'password' => $faker->password,
                ],
            ],
        ];
    }
}
